use anyhow::Result;
use colored::Colorize;
use std::fs;
use std::path::Path;

pub fn run(workspace: &Path) -> Result<()> {
    tracing::info!(workspace = %workspace.display(), "syncing management dashboard");
    println!("{}", "=== Sync Management Dashboard ===".cyan().bold());
    crate::common::capability_contract::require_policy_enabled(
        workspace,
        "reporting",
        "report dashboard",
    )?;

    // Read snapshot
    let snapshot_path = workspace.join(".state/reporting/report-snapshot.json");
    if !snapshot_path.exists() {
        tracing::info!(snapshot_path = %snapshot_path.display(), "report snapshot missing; building a fresh one");
        println!("  Snapshot not found — building first...");
        crate::reporting::snapshot::run(workspace)?;
    }

    let content = fs::read_to_string(&snapshot_path)?;
    let snapshot: serde_json::Value = serde_json::from_str(&content)?;

    let generated = snapshot["generated_at"].as_str().unwrap_or("unknown");
    let vision = snapshot["product"]["vision"].as_str().unwrap_or("N/A");

    let total_stories = snapshot["metrics"]["total_stories"].as_u64().unwrap_or(0);
    let total_handoffs = snapshot["metrics"]["total_handoffs"].as_u64().unwrap_or(0);
    let pending_handoffs = snapshot["metrics"]["pending_handoffs"]
        .as_u64()
        .unwrap_or(0);
    let total_findings = snapshot["metrics"]["total_findings"].as_u64().unwrap_or(0);
    let open_findings = snapshot["metrics"]["open_findings"].as_u64().unwrap_or(0);
    let total_releases = snapshot["metrics"]["total_releases"].as_u64().unwrap_or(0);

    // Build handoff table
    let mut handoff_rows = String::new();
    if let Some(handoffs) = snapshot["handoffs"].as_array() {
        for h in handoffs {
            let id = markdown_table_cell(h["id"].as_str().unwrap_or("?"));
            let from = markdown_table_cell(h["from"].as_str().unwrap_or("?"));
            let to = markdown_table_cell(h["to"].as_str().unwrap_or("?"));
            let status = markdown_table_cell(h["status"].as_str().unwrap_or("?"));
            let entity = markdown_table_cell(h["entity"].as_str().unwrap_or("?"));
            handoff_rows.push_str(&format!("| {id} | {from} | {to} | {status} | {entity} |\n"));
        }
    }
    if handoff_rows.is_empty() {
        handoff_rows = "| — | — | — | — | — |\n".to_string();
    }

    // Build findings table
    let mut finding_rows = String::new();
    if let Some(findings) = snapshot["findings"].as_array() {
        for f in findings {
            let id = markdown_table_cell(f["id"].as_str().unwrap_or("?"));
            let ftype = markdown_table_cell(f["type"].as_str().unwrap_or("?"));
            let severity = markdown_table_cell(f["severity"].as_str().unwrap_or("?"));
            let status = markdown_table_cell(f["status"].as_str().unwrap_or("?"));
            let title = markdown_table_cell(f["title"].as_str().unwrap_or("?"));
            finding_rows.push_str(&format!(
                "| {id} | {ftype} | {severity} | {status} | {title} |\n"
            ));
        }
    }
    if finding_rows.is_empty() {
        finding_rows = "| — | — | — | — | — |\n".to_string();
    }

    // Build releases table
    let mut release_rows = String::new();
    if let Some(releases) = snapshot["releases"].as_array() {
        for r in releases {
            let id = markdown_table_cell(r["id"].as_str().unwrap_or("?"));
            let name = markdown_table_cell(r["name"].as_str().unwrap_or("?"));
            let status = markdown_table_cell(r["status"].as_str().unwrap_or("planning"));
            let date = markdown_table_cell(r["target_date"].as_str().unwrap_or("?"));
            release_rows.push_str(&format!("| {id} | {name} | {status} | {date} |\n"));
        }
    }
    if release_rows.is_empty() {
        release_rows = "| — | — | — | — |\n".to_string();
    }

    let dashboard = format!(
        r#"# Management Dashboard

> Auto-generated by `prdtp-agents-functions-cli report dashboard` — Last updated: {generated}

## Product Vision

{vision}

## Key Metrics

| Metric | Value |
|--------|-------|
| Total Stories | {total_stories} |
| Total Handoffs | {total_handoffs} ({pending_handoffs} pending) |
| Total Findings | {total_findings} ({open_findings} open) |
| Total Releases | {total_releases} |

## Handoffs

| ID | From | To | Status | Entity |
|----|------|----|--------|--------|
{handoff_rows}
## Findings

| ID | Type | Severity | Status | Title |
|----|------|----------|--------|-------|
{finding_rows}
## Releases

| ID | Name | Status | Target Date |
|----|------|--------|-------------|
{release_rows}
"#
    );

    let dashboard_path = workspace.join("docs/project/management-dashboard.md");
    fs::write(&dashboard_path, &dashboard)?;

    tracing::info!(dashboard_path = %dashboard_path.display(), "management dashboard updated");

    println!(
        "{} Updated {}",
        "OK:".green().bold(),
        dashboard_path.display()
    );
    Ok(())
}

fn markdown_table_cell(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('|', "\\|")
        .replace('*', "\\*")
        .replace('_', "\\_")
        .replace('[', "\\[")
        .replace(']', "\\]")
        .replace('\n', "<br>")
}
