use anyhow::{bail, Result};
use clap::Args;
use colored::Colorize;
use std::fs;
use std::path::Path;
use std::process::Command;

#[derive(Args)]
pub struct SyncArgs {
    /// GitHub repository (owner/repo). Falls back to `gh repo view --json nameWithOwner`
    #[arg(long)]
    pub repo: Option<String>,
    /// Output file (defaults to docs/project/board.md)
    #[arg(long)]
    pub output: Option<String>,
}

pub fn run(workspace: &Path, args: SyncArgs) -> Result<()> {
    tracing::info!(workspace = %workspace.display(), repo = ?args.repo, output = ?args.output, "syncing GitHub board");
    crate::common::capability_contract::require_policy_enabled(
        workspace,
        "gh",
        "board sync",
    )?;

    // Resolve repo
    let repo = match args.repo {
        Some(r) => r,
        None => {
            let output = Command::new("gh")
                .args(["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"])
                .current_dir(workspace)
                .output();
            match output {
                Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout).trim().to_string(),
                Ok(o) => {
                    let stderr = String::from_utf8_lossy(&o.stderr).trim().to_string();
                    if !stderr.is_empty() {
                        tracing::debug!(stderr = %stderr, "gh repo view failed while resolving repository");
                    }
                    bail!("Could not determine repo. Pass --repo owner/repo or run from a GitHub repo with gh CLI.")
                }
                Err(error) => {
                    tracing::error!(error = %error, "failed to execute gh repo view while resolving repository");
                    bail!("Could not determine repo. Pass --repo owner/repo or run from a GitHub repo with gh CLI.")
                }
            }
        }
    };

    tracing::info!(repo = %repo, "resolved GitHub repository for board sync");
    println!("{} Syncing GitHub board for {repo}", "→".cyan());

    // Fetch open issues
    let issues_out = Command::new("gh")
        .args([
            "issue", "list", "--repo", &repo ,"--state", "open",
            "--json", "number,title,labels,assignees,state",
            "--limit", "200",
        ])
        .current_dir(workspace)
        .output()?;

    if !issues_out.status.success() {
        let stderr = String::from_utf8_lossy(&issues_out.stderr).trim().to_string();
        if !stderr.is_empty() {
            tracing::debug!(repo = %repo, stderr = %stderr, "gh issue list failed");
        }
        bail!(
            "gh issue list failed: {}",
            String::from_utf8_lossy(&issues_out.stderr)
        );
    }

    let issues: Vec<serde_json::Value> =
        serde_json::from_slice(&issues_out.stdout).unwrap_or_default();

    // Fetch open PRs
    let prs_out = Command::new("gh")
        .args([
            "pr", "list", "--repo", &repo, "--state", "open",
            "--json", "number,title,labels,author,state,isDraft",
            "--limit", "200",
        ])
        .current_dir(workspace)
        .output()?;

    if !prs_out.status.success() {
        let stderr = String::from_utf8_lossy(&prs_out.stderr).trim().to_string();
        if !stderr.is_empty() {
            tracing::debug!(repo = %repo, stderr = %stderr, "gh pr list failed");
        }
        bail!(
            "gh pr list failed: {}",
            String::from_utf8_lossy(&prs_out.stderr)
        );
    }

    let prs: Vec<serde_json::Value> =
        serde_json::from_slice(&prs_out.stdout).unwrap_or_default();

    // Build Markdown
    let mut md = String::from("# Project Board\n\n");
    md.push_str(&format!(
        "> Auto-generated by `prdtp-agents-functions-cli board sync` — {}\n\n",
        chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ")
    ));

    md.push_str("## Open Issues\n\n");
    if issues.is_empty() {
        md.push_str("_No open issues._\n\n");
    } else {
        md.push_str("| # | Title | Labels | Assignees |\n");
        md.push_str("|---|-------|--------|-----------|\n");
        for issue in &issues {
            let num = issue["number"].as_u64().unwrap_or(0);
            let title = issue["title"].as_str().unwrap_or("");
            let labels: Vec<&str> = issue["labels"]
                .as_array()
                .map(|arr| arr.iter().filter_map(|l| l["name"].as_str()).collect())
                .unwrap_or_default();
            let assignees: Vec<&str> = issue["assignees"]
                .as_array()
                .map(|arr| arr.iter().filter_map(|a| a["login"].as_str()).collect())
                .unwrap_or_default();
            md.push_str(&format!(
                "| #{num} | {title} | {} | {} |\n",
                labels.join(", "),
                assignees.join(", ")
            ));
        }
        md.push('\n');
    }

    md.push_str("## Open Pull Requests\n\n");
    if prs.is_empty() {
        md.push_str("_No open pull requests._\n\n");
    } else {
        md.push_str("| # | Title | Author | Draft | Labels |\n");
        md.push_str("|---|-------|--------|-------|--------|\n");
        for pr in &prs {
            let num = pr["number"].as_u64().unwrap_or(0);
            let title = pr["title"].as_str().unwrap_or("");
            let author = pr["author"]["login"].as_str().unwrap_or("?");
            let draft = if pr["isDraft"].as_bool().unwrap_or(false) {
                "yes"
            } else {
                "no"
            };
            let labels: Vec<&str> = pr["labels"]
                .as_array()
                .map(|arr| arr.iter().filter_map(|l| l["name"].as_str()).collect())
                .unwrap_or_default();
            md.push_str(&format!(
                "| #{num} | {title} | @{author} | {draft} | {} |\n",
                labels.join(", ")
            ));
        }
        md.push('\n');
    }

    md.push_str(&format!(
        "\n---\n_Issues: {} | PRs: {}_\n",
        issues.len(),
        prs.len()
    ));

    // Write output
    let output_path = match args.output {
        Some(ref o) => workspace.join(o),
        None => workspace.join("docs/project/board.md"),
    };
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&output_path, &md)?;

    tracing::info!(repo = %repo, issues = issues.len(), prs = prs.len(), output_path = %output_path.display(), "board sync completed");

    println!(
        "{} Board synced: {} issues, {} PRs → {}",
        "✓".green().bold(),
        issues.len(),
        prs.len(),
        output_path.display()
    );

    Ok(())
}
