use anyhow::{bail, Context, Result};
use clap::Args;
use colored::Colorize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

use crate::util;

// ── Args ─────────────────────────────────────────────────────────

#[derive(Args)]
pub struct WorkspaceArgs {
    /// Target workspace directory
    #[arg(long)]
    pub target: Option<PathBuf>,
    /// Project name (defaults to target folder name)
    #[arg(long)]
    pub project_name: Option<String>,
    /// GitHub owner
    #[arg(long)]
    pub github_owner: Option<String>,
    /// GitHub repository
    #[arg(long)]
    pub github_repo: Option<String>,
    /// Skip SQLite DB initialization
    #[arg(long)]
    pub skip_db_init: bool,
    /// Skip git commit
    #[arg(long)]
    pub skip_git: bool,
    /// Dry-run mode: list operations without executing
    #[arg(long)]
    pub dry_run: bool,
    /// Preflight only: show dependency status and exit
    #[arg(long)]
    pub preflight_only: bool,
}

#[derive(Args)]
pub struct CommitArgs {
    /// Target workspace directory
    #[arg(long)]
    pub target: Option<PathBuf>,
    /// Commit message
    #[arg(long)]
    pub message: Option<String>,
    /// Allow commits on main branch
    #[arg(long)]
    pub allow_main: bool,
}

// ── Manifest ─────────────────────────────────────────────────────

struct Manifest {
    records: BTreeMap<String, String>,
}

impl Manifest {
    fn new() -> Self {
        Self {
            records: BTreeMap::new(),
        }
    }

    fn set(&mut self, path: &str, kind: &str, ownership: &str, cleanup: &str) {
        let norm = path.replace('\\', "/");
        if norm.is_empty() {
            return;
        }
        self.records
            .insert(norm.clone(), format!("{norm}\t{kind}\t{ownership}\t{cleanup}"));
    }

    fn write(&self, path: &Path) -> Result<()> {
        let mut lines = vec!["# path\tkind\townership\tcleanup_action".to_string()];
        lines.extend(self.records.values().cloned());
        util::write_utf8_lf(path, &(lines.join("\n") + "\n"))
    }
}

// ── Dynamic files that are regenerated by bootstrap scripts ──────
const DYNAMIC_GENERATED: &[&str] = &[
    ".github/CODEOWNERS",
    ".github/workspace-capabilities.yaml",
    ".github/github-governance.yaml",
    "docs/project/vision.md",
    "docs/project/scope.md",
    "docs/project/stakeholders.md",
];

// ── Token files ──────────────────────────────────────────────────
const TOKEN_FILES: &[&str] = &[
    "docs/project/vision.md",
    "docs/project/scope.md",
    "docs/project/stakeholders.md",
    ".github/github-governance.yaml",
];

const MANAGED_BLOCK_PREFIX: &str = "bootstrap-product-agent-workspace";

// ── Bootstrap workspace ──────────────────────────────────────────

pub fn workspace(skill_root: &Path, args: WorkspaceArgs) -> Result<()> {
    tracing::info!(
        skill_root = %skill_root.display(),
        dry_run = args.dry_run,
        preflight_only = args.preflight_only,
        skip_db_init = args.skip_db_init,
        skip_git = args.skip_git,
        "starting workspace bootstrap"
    );

    let version = util::read_version(skill_root)?;

    // Validate SKILL.md matches VERSION
    let skill_md = skill_root.join("SKILL.md");
    if skill_md.exists() {
        let content = fs::read_to_string(&skill_md)?;
        let pattern = format!("skill-version: {version}");
        if !content.contains(&pattern) {
            bail!("SKILL.md skill-version does not match VERSION ({version})");
        }
    } else {
        bail!("SKILL.md not found at {}", skill_md.display());
    }

    let template_root = skill_root.join("templates").join("workspace");
    if !template_root.is_dir() {
        bail!(
            "Template directory not found: {}",
            template_root.display()
        );
    }

    let target_root = args
        .target
        .as_deref()
        .unwrap_or(Path::new("."));
    let target_root = target_root
        .canonicalize()
        .unwrap_or_else(|_| target_root.to_path_buf());

    // Guard: prevent bootstrapping into the skill's own templates directory
    let template_norm = template_root.to_string_lossy().replace('\\', "/");
    let target_norm = target_root.to_string_lossy().replace('\\', "/");
    if target_norm == template_norm || target_norm.starts_with(&format!("{template_norm}/")) {
        bail!("Target path is inside the skill template directory. Run this targeting a workspace root, not the template folder.");
    }

    let project_name = args
        .project_name
        .unwrap_or_else(|| {
            target_root
                .file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_else(|| "Unnamed Project".to_string())
        });

    // ── Preflight ─────────────────────────────────────────────
    show_preflight(&target_root, &project_name, skill_root);

    if args.preflight_only {
        println!(
            "\n{}",
            "Preflight complete. No files were written."
                .yellow()
        );
        return Ok(());
    }

    // ── Dry run ───────────────────────────────────────────────
    if args.dry_run {
        return dry_run(&template_root, &target_root);
    }
    let binary_bundle_lines = verify_binary_bundle_integrity(skill_root)?;

    // ── Main bootstrap ────────────────────────────────────────
    let overlay_root = target_root.join(".bootstrap-overlays");
    let state_dir = target_root.join(".state");
    let manifest_path = state_dir.join("bootstrap-manifest.txt");
    let report_path = state_dir.join("bootstrap-report.md");

    fs::create_dir_all(&overlay_root)?;
    fs::create_dir_all(&state_dir)?;

    let mut manifest = Manifest::new();
    let mut created: Vec<String> = Vec::new();
    let mut merged: Vec<String> = Vec::new();
    let mut overlays: Vec<String> = Vec::new();
    let mut collisions: Vec<String> = Vec::new();
    let mut touched: Vec<String> = Vec::new();

    // Walk template and copy/merge/overlay
    for entry in WalkDir::new(&template_root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        let source = entry.path();
        let relative = util::to_relative_posix(source, &template_root);
        let target_file = target_root.join(relative.replace('/', std::path::MAIN_SEPARATOR_STR));

        if let Some(parent) = target_file.parent() {
            fs::create_dir_all(parent)?;
        }

        if !target_file.exists() {
            // New file: copy
            fs::copy(source, &target_file)?;
            created.push(relative.clone());
            touched.push(relative.clone());
            manifest.set(&relative, "template_copy", "skill", "delete");
        } else if DYNAMIC_GENERATED.contains(&relative.as_str()) {
            // Skip dynamically generated files
            touched.push(relative.clone());
            manifest.set(&relative, "dynamic_generated", "skill", "keep");
        } else {
            // Check for differences
            let source_hash = file_sha256(source)?;
            let target_hash = file_sha256(&target_file)?;

            if source_hash != target_hash {
                if relative == "AGENTS.md" || relative == ".instructions.md" {
                    let block_name = if relative == "AGENTS.md" {
                        "agents-md"
                    } else {
                        "instructions-md"
                    };
                    if merge_managed_block(&target_file, source, block_name)? {
                        touched.push(relative.clone());
                        merged.push(relative.clone());
                        manifest.set(&relative, "managed_merge", "host", "keep");
                        println!("  {} {} (managed block)", "MERGED:".cyan(), relative);
                    }
                } else if relative == ".gitignore" || relative == ".gitattributes" {
                    let new_count = merge_line_entries(&target_file, source)?;
                    if new_count > 0 {
                        touched.push(relative.clone());
                        merged.push(relative.clone());
                        manifest.set(&relative, "line_merge", "host", "keep");
                        println!(
                            "  {} {} (appended {new_count} entries)",
                            "MERGED:".cyan(),
                            relative
                        );
                    }
                } else {
                    // Overlay proposal
                    let overlay_file =
                        overlay_root.join(format!("{}.new", relative.replace('/', std::path::MAIN_SEPARATOR_STR)));
                    if let Some(p) = overlay_file.parent() {
                        fs::create_dir_all(p)?;
                    }
                    fs::copy(source, &overlay_file)?;
                    let ov_rel = util::to_relative_posix(&overlay_file, &target_root);
                    overlays.push(ov_rel.clone());
                    collisions.push(relative.clone());
                    touched.push(ov_rel.clone());
                    manifest.set(&ov_rel, "overlay_copy", "skill", "delete");
                }
            } else {
                manifest.set(&relative, "template_copy", "skill", "delete");
            }
        }
    }

    // ── Token replacement ─────────────────────────────────────
    let github_owner = args.github_owner.as_deref().unwrap_or("");
    let github_repo = args.github_repo.as_deref().unwrap_or("");

    for token_file in TOKEN_FILES {
        let file_path = target_root.join(token_file);
        if file_path.exists() {
            let mut content = fs::read_to_string(&file_path)?;
            let mut changed = false;

            if content.contains("{{PROJECT_NAME}}") {
                content = content.replace("{{PROJECT_NAME}}", &project_name);
                changed = true;
            }
            if !github_owner.is_empty() && content.contains("REPLACE_ME_GITHUB_OWNER") {
                content = content.replace("REPLACE_ME_GITHUB_OWNER", github_owner);
                changed = true;
            }
            if !github_repo.is_empty() && content.contains("REPLACE_ME_GITHUB_REPOSITORY") {
                content = content.replace("REPLACE_ME_GITHUB_REPOSITORY", github_repo);
                changed = true;
            }

            if changed {
                tracing::info!(path = %file_path.display(), "applying transactional token replacement");
                let temp_path = file_path.with_extension("tmp");
                util::write_utf8_lf(&temp_path, &content)?;
                
                let read_back = fs::read_to_string(&temp_path)?;
                if read_back != content {
                    let _ = fs::remove_file(&temp_path);
                    anyhow::bail!("Failed to verify token replacement on {}", file_path.display());
                }
                
                fs::rename(&temp_path, &file_path)?;

                if !touched.contains(&token_file.to_string()) {
                    touched.push(token_file.to_string());
                }
            }
        }
    }

    // ── Run capability refresh ────────────────────────────────
    let caps_path = target_root.join(".github").join("workspace-capabilities.yaml");
    if let Err(e) = write_capabilities_yaml(&target_root, &caps_path) {
        tracing::warn!(error = %e, capabilities_path = %caps_path.display(), "capability detection failed during bootstrap");
        eprintln!("  {} capability detection: {e}", "WARN:".yellow());
    }
    let _ = mark_workspace_bootstrapped(&target_root);

    // ── Write report ──────────────────────────────────────────
    let _backup = util::backup_with_retention(&report_path, 3)?;

    let git_status_str = format!("{}", if util::command_exists("git") { "available" } else { "missing" });
    let sqlite_status_str = format!("{}", if util::command_exists("sqlite3") { "available" } else { "missing" });
    let mdlint_status_str = if util::command_exists("markdownlint") {
        "available".to_string()
    } else {
        "not installed (optional)".to_string()
    };

    let mut report = vec![
        "# Bootstrap Report".to_string(),
        String::new(),
        "## Skill Version".to_string(),
        String::new(),
        format!("<!-- skill-version: {version} -->"),
        format!("- Version: {version}"),
        String::new(),
        "## Preflight".to_string(),
        String::new(),
        format!("- Project Name: {project_name}"),
        format!("- Runner: {}", skill_root.display()),
        format!("- Target: {}", target_root.display()),
        format!("- Git: {git_status_str}"),
        format!("- sqlite3: {sqlite_status_str}"),
        format!("- markdownlint: {mdlint_status_str}"),
        String::new(),
        "## Created Files".to_string(),
    ];

    if created.is_empty() {
        report.push("- None".to_string());
    } else {
        for f in &created {
            report.push(format!("- {f}"));
        }
    }

    report.push(String::new());
    report.push("## Merged Host Files".to_string());
    if merged.is_empty() {
        report.push("- None".to_string());
    } else {
        let mut unique_merged: Vec<_> = merged.clone();
        unique_merged.sort();
        unique_merged.dedup();
        for f in &unique_merged {
            report.push(format!("- {f} (preserved during cleanup)"));
        }
    }

    report.push(String::new());
    report.push("## Overlay Proposals".to_string());
    if overlays.is_empty() {
        report.push("- None".to_string());
    } else {
        for f in &overlays {
            report.push(format!("- {f}"));
        }
    }

    report.push(String::new());
    report.push("## Collisions".to_string());
    if collisions.is_empty() {
        report.push("- None".to_string());
    } else {
        for f in &collisions {
            report.push(format!("- {f}"));
        }
    }

    util::write_utf8_lf(&report_path, &(report.join("\n") + "\n"))?;
    manifest.set(
        ".state/bootstrap-manifest.txt",
        "generated_runtime",
        "skill",
        "delete",
    );
    manifest.set(
        ".state/bootstrap-report.md",
        "generated_runtime",
        "skill",
        "delete",
    );
    manifest.write(&manifest_path)?;

    // ── SQLite init (via sqlite3 CLI) ─────────────────────────
    let mut bootstrap_status = "FULL";
    if !args.skip_db_init {
        if util::command_exists("sqlite3") {
            let db_path = target_root.join(".state").join("project_memory.db");
            if !db_path.exists() {
                let schema_path = target_root.join(".state").join("memory-schema.sql");
                if schema_path.exists() {
                    let status = std::process::Command::new("sqlite3")
                        .arg(db_path.to_string_lossy().as_ref())
                        .arg(format!(".read \"{}\"", schema_path.to_string_lossy().replace('\\', "/")))
                        .status();
                    match status {
                        Ok(s) if s.success() => {
                            tracing::info!(database_path = %db_path.display(), "sqlite database initialized during bootstrap");
                            println!("  {} SQLite DB initialized", "OK:".green());
                        }
                        _ => {
                            tracing::warn!(database_path = %db_path.display(), "sqlite database initialization failed during bootstrap");
                            eprintln!("  {} SQLite DB init failed", "WARN:".yellow());
                            bootstrap_status = "DEGRADED";
                        }
                    }
                }
            }
        } else {
            tracing::warn!("sqlite3 not found; bootstrap database initialization deferred");
            eprintln!(
                "  {} sqlite3 not found -- DB init deferred",
                "WARN:".yellow()
            );
            bootstrap_status = "DEGRADED";
        }
    }

    // Append bootstrap status to report
    let status_section = format!(
        "\n## Bootstrap Status\n\n- Status: {bootstrap_status}{}\n",
        if bootstrap_status == "DEGRADED" {
            "\n- Reason: sqlite3 not available -- DB init deferred\n- Action: Install sqlite3 and run `prdtp-agents-functions-cli database init` manually"
        } else {
            ""
        }
    );
    util::append_utf8_lf(&report_path, &status_section)?;

    // ── Workspace validation ──────────────────────────────────
    let validation_pass = run_workspace_validation(&target_root);
    let governance_status = detect_governance_status(&target_root);
    let readiness_status = detect_readiness_status(&target_root, governance_status);
    let manual_next_steps = collect_manual_next_steps(
        &target_root,
        governance_status,
        github_owner,
        github_repo,
    );

    // ── Git commit ────────────────────────────────────────────
    #[allow(unused_assignments)]
    let mut git_commit_state = String::new();
    if !args.skip_git && util::command_exists("git") {
        let caps_path_check = target_root.join(".github").join("workspace-capabilities.yaml");
        let git_enabled = util::yaml_bool(&caps_path_check, "capabilities.git.policy.enabled", true);

        if git_enabled {
            if has_git_identity(&target_root) {
                // Initialize git if needed
                if !target_root.join(".git").exists() {
                    let _ = std::process::Command::new("git")
                        .args(["-c", "init.defaultBranch=main", "init"])
                        .current_dir(&target_root)
                        .status();
                }
                match run_safe_commit(&target_root, &manifest_path, "chore: bootstrap product-agent workspace", true) {
                    Ok(hash) => {
                        tracing::info!(commit = %hash, "bootstrap git commit created");
                        git_commit_state = hash;
                    }
                    Err(e) => {
                        tracing::warn!(error = %e, "bootstrap git commit failed");
                        eprintln!("  {} git commit: {e}", "WARN:".yellow());
                        git_commit_state = "failed".to_string();
                    }
                }
            } else {
                git_commit_state = "skipped (identity missing)".to_string();
            }
        } else {
            git_commit_state = "skipped (git disabled)".to_string();
        }
    } else if args.skip_git {
        git_commit_state = "skipped".to_string();
    } else {
        git_commit_state = "skipped (git not found)".to_string();
    }

    // ── Git hooks ─────────────────────────────────────────────
    let hooks_installed = if target_root.join(".git").exists() {
        install_pre_commit_hook(&target_root).is_ok()
    } else {
        false
    };

    // ── Append git section to report ──────────────────────────
    let git_section = format!("\n## Git Commit\n\n- Status: {git_commit_state}\n");
    util::append_utf8_lf(&report_path, &git_section)?;
    let binary_bundle_section = format!(
        "\n## Binary Bundle Integrity\n\n- Status: pass\n{}\n",
        binary_bundle_lines
            .iter()
            .map(|line| format!("- {line}"))
            .collect::<Vec<_>>()
            .join("\n")
    );
    util::append_utf8_lf(&report_path, &binary_bundle_section)?;
    let workspace_state_section = format!(
        "\n## Workspace State\n\n- Template State: template\n- Workspace State: bootstrapped\n- Structure validation: {}\n- Governance status: {}\n- Readiness status: {}\n",
        if validation_pass { "pass" } else { "fail" },
        governance_status,
        readiness_status
    );
    util::append_utf8_lf(&report_path, &workspace_state_section)?;
    let manual_steps_section = if manual_next_steps.is_empty() {
        "\n## Manual Next Steps\n\n- None\n".to_string()
    } else {
        let mut section = String::from("\n## Manual Next Steps\n\n");
        for step in &manual_next_steps {
            section.push_str(&format!("- {step}\n"));
        }
        section
    };
    util::append_utf8_lf(&report_path, &manual_steps_section)?;

    // ── Summary ───────────────────────────────────────────────
    let db_exists = target_root
        .join(".state")
        .join("project_memory.db")
        .exists();

    if !validation_pass {
        println!("\n{}", "===================================================".red());
        println!("  {} {bootstrap_status}", "BOOTSTRAP INCOMPLETE -".red());
        println!("{}", "===================================================".red());
    } else {
        println!("\n{}", "===================================================".green());
        println!("  {} {bootstrap_status}", "BOOTSTRAP COMPLETE -".green());
        println!("{}", "===================================================".green());
    }
    println!();
    println!("  Project:      {project_name}");
    println!("  Target:       {}", target_root.display());
    println!();
    println!("  {}", "--- Component Status ---".cyan());
    println!(
        "  Bootstrap:       {}",
        if bootstrap_status == "FULL" {
            bootstrap_status.green().to_string()
        } else {
            bootstrap_status.yellow().to_string()
        }
    );
    println!("  Files created:   {}", format!("{}", created.len()).green());
    let unique_merged_count = {
        let mut m = merged.clone();
        m.sort();
        m.dedup();
        m.len()
    };
    println!("  Host merges:     {unique_merged_count}");
    println!("  Overlays:        {} proposals", overlays.len());
    println!("  Collisions:      {}", collisions.len());
    println!(
        "  Validation:      {}",
        if validation_pass { "PASS".green().to_string() } else { "FAIL".red().to_string() }
    );
    println!("  Governance:      {governance_status}");
    println!("  Readiness:       {readiness_status}");
    println!(
        "  SQLite DB:       {}",
        if db_exists { "initialized".green().to_string() } else { "pending".yellow().to_string() }
    );
    println!("  Git commit:      {git_commit_state}");
    println!(
        "  Git hooks:       {}",
        if hooks_installed { "installed" } else { "not installed" }
    );
    println!();
    println!("  Report:   .state/bootstrap-report.md");
    println!("  Manifest: .state/bootstrap-manifest.txt");
    println!("{}", "===================================================".green());

    tracing::info!(
        target = %target_root.display(),
        created = created.len(),
        merged = unique_merged_count,
        overlays = overlays.len(),
        collisions = collisions.len(),
        validation_pass,
        bootstrap_status,
        "workspace bootstrap completed"
    );

    if !validation_pass {
        std::process::exit(1);
    }
    Ok(())
}

// ── Safe git commit ──────────────────────────────────────────────

pub fn commit(_skill_root: &Path, args: CommitArgs) -> Result<()> {
    let target = args
        .target
        .as_deref()
        .unwrap_or(Path::new("."));
    let target = target.canonicalize().unwrap_or_else(|_| target.to_path_buf());
    let manifest_path = target.join(".state").join("bootstrap-manifest.txt");
    let message = args
        .message
        .unwrap_or_else(|| "chore: bootstrap product-agent workspace".to_string());

    if !manifest_path.exists() {
        bail!(
            "Missing bootstrap manifest: {}",
            manifest_path.display()
        );
    }

    // Check git capability
    let caps_path = target.join(".github").join("workspace-capabilities.yaml");
    if caps_path.exists() && !util::yaml_bool(&caps_path, "capabilities.git.policy.enabled", true) {
        println!(
            "{}",
            "Skipping git commit: Git capability disabled by .github/workspace-capabilities.yaml."
                .yellow()
        );
        return Ok(());
    }

    if !util::command_exists("git") {
        bail!("git is not available");
    }

    let hash = run_safe_commit(&target, &manifest_path, &message, args.allow_main)?;
    if hash.is_empty() {
        println!(
            "{}",
            "No committable bootstrap changes to commit.".yellow()
        );
    } else {
        println!("{} {hash}", "Committed as".green());
    }
    Ok(())
}

// ── Helpers ──────────────────────────────────────────────────────

fn show_preflight(target: &Path, project_name: &str, runner: &Path) {
    println!("\n{}", "--- Bootstrap preflight ---".cyan());
    println!("Runner:       {}", runner.display());
    println!("Target:       {}", target.display());
    println!("Project:      {project_name}");
    println!(
        "Git:          {}",
        if util::command_exists("git") {
            "available"
        } else {
            "missing"
        }
    );
    println!(
        "gh:           {}",
        if util::command_exists("gh") {
            "available"
        } else {
            "missing"
        }
    );
    println!(
        "sqlite3:      {}",
        if util::command_exists("sqlite3") {
            "available"
        } else {
            "missing"
        }
    );
    println!(
        "markdownlint: {}",
        if util::command_exists("markdownlint") {
            "available"
        } else {
            "not installed (optional)"
        }
    );
}

fn dry_run(template_root: &Path, target_root: &Path) -> Result<()> {
    println!("\n{}", "--- DRY RUN (no files will be written) ---".cyan());
    let mut would_create = 0u32;
    let mut would_overlay = 0u32;
    let mut would_skip = 0u32;

    for entry in WalkDir::new(template_root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        let source = entry.path();
        let relative = util::to_relative_posix(source, template_root);
        let target_file = target_root.join(relative.replace('/', std::path::MAIN_SEPARATOR_STR));

        if !target_file.exists() {
            println!("  {} {relative}", "CREATE:".green());
            would_create += 1;
        } else if DYNAMIC_GENERATED.contains(&relative.as_str()) {
            would_skip += 1;
        } else {
            let sh = file_sha256(source)?;
            let th = file_sha256(&target_file)?;
            if sh != th {
                println!("  {} {relative} (collision)", "OVERLAY:".yellow());
                would_overlay += 1;
            } else {
                would_skip += 1;
            }
        }
    }

    println!("\n{}", "--- Dry run summary ---".cyan());
    println!("  Would create:  {would_create} files");
    println!("  Would overlay: {would_overlay} proposals");
    println!("  Would skip:    {would_skip} unchanged files");
    Ok(())
}

fn file_sha256(path: &Path) -> Result<String> {
    let content = fs::read(path).with_context(|| format!("reading {}", path.display()))?;
    let mut hasher = Sha256::new();
    hasher.update(&content);
    Ok(format!("{:x}", hasher.finalize()))
}

fn verify_binary_bundle_integrity(skill_root: &Path) -> Result<Vec<String>> {
    let mut lines = Vec::new();
    lines.push(verify_checksum_manifest(
        &skill_root.join("bin"),
        "checksums.sha256",
        "skill bootstrap bundle",
    )?);
    lines.push(verify_checksum_manifest(
        &skill_root
            .join("templates")
            .join("workspace")
            .join(".agents")
            .join("bin")
            .join("prd-to-product-agents"),
        "checksums.sha256",
        "workspace runtime bundle",
    )?);
    Ok(lines)
}

fn verify_checksum_manifest(bundle_dir: &Path, manifest_name: &str, label: &str) -> Result<String> {
    let manifest_path = bundle_dir.join(manifest_name);
    if !manifest_path.is_file() {
        bail!(
            "{label} checksum manifest not found: {}",
            manifest_path.display()
        );
    }

    let manifest = fs::read_to_string(&manifest_path)?;
    let mut expected: Vec<(String, String)> = Vec::new();
    for (index, line) in manifest.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let mut parts = trimmed.split_whitespace();
        let Some(hash) = parts.next() else {
            bail!("{label} checksum manifest line {} is malformed", index + 1);
        };
        let Some(file_name) = parts.next() else {
            bail!("{label} checksum manifest line {} is malformed", index + 1);
        };
        if parts.next().is_some() {
            bail!("{label} checksum manifest line {} is malformed", index + 1);
        }
        expected.push((hash.to_ascii_lowercase(), file_name.to_string()));
    }

    if expected.is_empty() {
        bail!("{label} checksum manifest is empty");
    }

    let actual_files: Vec<String> = fs::read_dir(bundle_dir)?
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.file_type().map(|kind| kind.is_file()).unwrap_or(false))
        .map(|entry| entry.file_name().to_string_lossy().to_string())
        .filter(|name| name != manifest_name)
        .collect();

    let mut errors = Vec::new();
    for (expected_hash, file_name) in &expected {
        let file_path = bundle_dir.join(file_name);
        if !file_path.is_file() {
            errors.push(format!("missing {file_name}"));
            continue;
        }
        let actual_hash = file_sha256(&file_path)?;
        if actual_hash.to_ascii_lowercase() != *expected_hash {
            errors.push(format!("checksum mismatch for {file_name}"));
        }
    }

    for file_name in &actual_files {
        if !expected.iter().any(|(_, expected_name)| expected_name == file_name) {
            errors.push(format!("untracked bundled file {file_name}"));
        }
    }

    if errors.is_empty() {
        Ok(format!(
            "{label}: pass ({})",
            manifest_path
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or(manifest_name)
        ))
    } else {
        bail!("{label} integrity failed:\n  {}", errors.join("\n  "))
    }
}

fn merge_managed_block(target: &Path, source: &Path, block_name: &str) -> Result<bool> {
    let existing = fs::read_to_string(target)?;
    let template_raw = fs::read_to_string(source)?;

    let start_marker = format!("<!-- {MANAGED_BLOCK_PREFIX}:{block_name}:start -->");
    let end_marker = format!("<!-- {MANAGED_BLOCK_PREFIX}:{block_name}:end -->");

    let should_demote_headings = if let (Some(start_idx), Some(end_idx)) = (
        existing.find(&start_marker),
        existing.find(&end_marker),
    ) {
        let before = existing[..start_idx].trim();
        let after = existing[end_idx + end_marker.len()..].trim();
        !before.is_empty() || !after.is_empty()
    } else {
        !existing.trim().is_empty()
    };

    let template = prepare_managed_block_template(&template_raw, block_name, should_demote_headings)
        .trim_matches(&['\r', '\n'] as &[char])
        .to_string();
    let managed_block = format!("{start_marker}\n{template}\n{end_marker}");

    let updated = if let (Some(start_idx), Some(end_idx)) = (
        existing.find(&start_marker),
        existing.find(&end_marker),
    ) {
        if end_idx > start_idx {
            let before = existing[..start_idx].trim_end_matches(&['\r', '\n'] as &[char]);
            let after = existing[end_idx + end_marker.len()..]
                .trim_start_matches(&['\r', '\n'] as &[char]);
            let mut result = if before.is_empty() {
                managed_block.clone()
            } else {
                format!("{before}\n\n{managed_block}")
            };
            if !after.is_empty() {
                result = format!("{result}\n\n{after}");
            }
            if !result.ends_with('\n') {
                result.push('\n');
            }
            result
        } else {
            return Ok(false);
        }
    } else {
        let mut result = existing.trim_end_matches(&['\r', '\n'] as &[char]).to_string();
        if !result.is_empty() {
            result.push_str("\n\n");
        }
        result.push_str(&managed_block);
        if !result.ends_with('\n') {
            result.push('\n');
        }
        result
    };

    if updated == existing {
        return Ok(false);
    }

    util::write_utf8_lf(target, &updated)?;
    Ok(true)
}

fn prepare_managed_block_template(template: &str, block_name: &str, should_demote_headings: bool) -> String {
    if should_demote_headings && block_name == "agents-md" {
        strip_root_agents_heading(template)
    } else if should_demote_headings && block_name == "instructions-md" {
        demote_markdown_headings(template, 1)
    } else {
        template.to_string()
    }
}

fn strip_root_agents_heading(markdown: &str) -> String {
    let mut removed_heading = false;
    let mut skipping_post_heading_blanks = false;
    let mut output: Vec<&str> = Vec::new();

    for line in markdown.lines() {
        if !removed_heading && line.trim() == "# AGENTS" {
            removed_heading = true;
            skipping_post_heading_blanks = true;
            continue;
        }

        if skipping_post_heading_blanks && line.trim().is_empty() {
            continue;
        }

        skipping_post_heading_blanks = false;

        output.push(line);
    }

    output.join("\n")
}

fn demote_markdown_headings(markdown: &str, levels: usize) -> String {
    let mut in_fence = false;
    let mut fence_marker = String::new();
    let mut output: Vec<String> = Vec::new();

    for line in markdown.lines() {
        let trimmed = line.trim_start();

        if let Some(marker) = fence_marker_for_line(trimmed) {
            if !in_fence {
                in_fence = true;
                fence_marker = marker.to_string();
            } else if trimmed.starts_with(&fence_marker) {
                in_fence = false;
                fence_marker.clear();
            }
            output.push(line.to_string());
            continue;
        }

        if !in_fence {
            let indent_len = line.len() - trimmed.len();
            let heading_level = trimmed.chars().take_while(|c| *c == '#').count();
            if (1..=6).contains(&heading_level) {
                let heading_body = &trimmed[heading_level..];
                if heading_body.starts_with(' ') {
                    let new_level = usize::min(heading_level + levels, 6);
                    let indent = &line[..indent_len];
                    output.push(format!("{indent}{}{heading_body}", "#".repeat(new_level)));
                    continue;
                }
            }
        }

        output.push(line.to_string());
    }

    output.join("\n")
}

fn fence_marker_for_line(trimmed: &str) -> Option<&'static str> {
    if trimmed.starts_with("```") {
        Some("```")
    } else if trimmed.starts_with("~~~") {
        Some("~~~")
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::{demote_markdown_headings, prepare_managed_block_template, strip_root_agents_heading};

    #[test]
    fn keeps_standalone_agents_headings_for_new_file_copy() {
        let input = "# AGENTS\n\n## PRD-to-Product Workspace Agents\n\n### Start Here\n\n```markdown\n# Inside fence\n```\n";
        let output = prepare_managed_block_template(input, "agents-md", false);

        assert_eq!(output, input);
    }

    #[test]
    fn strips_root_agents_heading_when_merging_into_existing_doc() {
        let input = "# AGENTS\n\n## PRD-to-Product Workspace Agents\n\n### Start Here\n";
        let output = prepare_managed_block_template(input, "agents-md", true);

        assert_eq!(output, "## PRD-to-Product Workspace Agents\n\n### Start Here");
    }

    #[test]
    fn does_not_demote_headings_inside_fenced_code_blocks() {
        let input = "# Agents\n\n```markdown\n# Inside fence\n## Still inside\n```\n";
        let output = demote_markdown_headings(input, 1);

        assert_eq!(
            output,
            "## Agents\n\n```markdown\n# Inside fence\n## Still inside\n```"
        );
    }

    #[test]
    fn strips_only_the_root_agents_heading() {
        let input = "<!-- markdownlint-disable MD013 -->\n\n# AGENTS\n\n## Section\n\n### Child\n";
        let output = strip_root_agents_heading(input);

        assert_eq!(
            output,
            "<!-- markdownlint-disable MD013 -->\n\n## Section\n\n### Child"
        );
    }
}

fn merge_line_entries(target: &Path, source: &Path) -> Result<usize> {
    let existing_content = fs::read_to_string(target)?;
    let template_content = fs::read_to_string(source)?;

    let existing_lines: std::collections::HashSet<String> = existing_content
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty())
        .collect();

    let new_entries: Vec<String> = template_content
        .lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty() && !existing_lines.contains(l))
        .collect();

    if new_entries.is_empty() {
        return Ok(0);
    }

    let label = if target
        .file_name()
        .map_or(false, |n| n == ".gitignore")
    {
        "Bootstrap workspace entries"
    } else {
        "Bootstrap workspace attributes"
    };

    let append = format!("\n# --- {label} ---\n{}\n", new_entries.join("\n"));
    util::append_utf8_lf(target, &append)?;
    Ok(new_entries.len())
}

fn write_capabilities_yaml(target_root: &Path, caps_path: &Path) -> Result<()> {
    let os = util::detect_os();
    let host = util::detect_host();
    let git_installed = util::command_exists("git");
    let git_identity = if git_installed {
        has_git_identity(target_root)
    } else {
        false
    };
    let gh_installed = util::command_exists("gh");
    let gh_authenticated = if gh_installed {
        util::command_ok("gh", &["auth", "status"])
    } else {
        false
    };
    let sqlite_installed = util::command_exists("sqlite3");
    let db_initialized = target_root
        .join(".state")
        .join("project_memory.db")
        .exists();
    let node_installed = util::command_exists("node");
    let npm_installed = util::command_exists("npm");
    let markdownlint_installed = util::command_exists("markdownlint");

    // Preserve existing policies on re-run
    let existing_updated = util::yaml_scalar(caps_path, "last_updated").ok().flatten();
    let preserve = existing_updated
        .as_deref()
        .map_or(false, |v| !v.is_empty() && v != "1970-01-01T00:00:00Z");

    let git_enabled = if preserve {
        util::yaml_bool(caps_path, "capabilities.git.policy.enabled", git_installed && git_identity)
    } else {
        git_installed && git_identity
    };
    let gh_enabled = if preserve {
        util::yaml_bool(caps_path, "capabilities.gh.policy.enabled", gh_installed && gh_authenticated) && git_enabled
    } else {
        gh_installed && gh_authenticated && git_enabled
    };
    let sqlite_enabled = if preserve {
        util::yaml_bool(caps_path, "capabilities.sqlite.policy.enabled", sqlite_installed)
    } else {
        sqlite_installed
    };
    let mdlint_enabled = if preserve {
        util::yaml_bool(caps_path, "capabilities.markdownlint.policy.enabled", markdownlint_installed)
    } else {
        markdownlint_installed
    };
    let local_history_enabled = if preserve {
        util::yaml_bool(caps_path, "capabilities.local_history.policy.enabled", true)
    } else {
        true
    };

    let b = |v: bool| if v { "true" } else { "false" };
    let yaml = format!(
        r#"schema_version: 1
environment:
  host: {host}
  os: {os}
capabilities:
  git:
    detected:
      installed: {git_installed}
      identity_configured: {git_identity}
    policy:
      enabled: {git_enabled}
      mode: {git_mode}
  gh:
    detected:
      installed: {gh_installed}
      authenticated: {gh_auth}
    policy:
      enabled: {gh_enabled}
  sqlite:
    detected:
      installed: {sqlite_installed}
      db_initialized: {db_init}
    policy:
      enabled: {sqlite_enabled}
      mode: {sqlite_mode}
  node:
    detected:
      installed: {node_installed}
      npm_installed: {npm_installed}
      native_linux: {node_native}
  markdownlint:
    detected:
      installed: {mdlint_installed}
      native_linux: {mdlint_native}
    policy:
      enabled: {mdlint_enabled}
  local_history:
    policy:
      enabled: {local_history}
      format: markdown+json
      path: .state/local-history
last_updated: {ts}
"#,
        git_installed = b(git_installed),
        git_identity = b(git_identity),
        git_enabled = b(git_enabled),
        git_mode = if git_enabled { "full" } else { "local-only" },
        gh_installed = b(gh_installed),
        gh_auth = b(gh_authenticated),
        gh_enabled = b(gh_enabled),
        sqlite_installed = b(sqlite_installed),
        db_init = b(db_initialized),
        sqlite_enabled = b(sqlite_enabled),
        sqlite_mode = if sqlite_enabled { "ledger" } else { "spool-only" },
        node_installed = b(node_installed),
        npm_installed = b(npm_installed),
        node_native = b(node_installed), // simplified
        mdlint_installed = b(markdownlint_installed),
        mdlint_native = b(markdownlint_installed), // simplified
        mdlint_enabled = b(mdlint_enabled),
        local_history = b(local_history_enabled),
        ts = util::now_utc(),
    );

    util::write_utf8_lf(caps_path, &yaml)
}

fn has_git_identity(target: &Path) -> bool {
    let name = std::process::Command::new("git")
        .args(["config", "--get", "user.name"])
        .current_dir(target)
        .output()
        .map(|o| !o.stdout.is_empty())
        .unwrap_or(false);
    let email = std::process::Command::new("git")
        .args(["config", "--get", "user.email"])
        .current_dir(target)
        .output()
        .map(|o| !o.stdout.is_empty())
        .unwrap_or(false);
    name && email
}

fn run_safe_commit(target: &Path, manifest_path: &Path, message: &str, allow_main: bool) -> Result<String> {
    if !util::command_exists("git") {
        bail!("git is not available");
    }

    // Initialize git if needed
    if !target.join(".git").exists() {
        std::process::Command::new("git")
            .args(["-c", "init.defaultBranch=main", "init"])
            .current_dir(target)
            .status()?;
    }

    // Branch guard
    if !allow_main {
        let branch = util::command_output("git", &["-C", &target.to_string_lossy(), "branch", "--show-current"])?;
        if branch == "main" {
            bail!("Refusing to commit on 'main'. Use -AllowMain for bootstrap-only commits.");
        }
    }

    // Read manifest lines
    let manifest_content = fs::read_to_string(manifest_path)?;
    let runtime_state = [
        ".state/bootstrap-manifest.txt",
        ".state/bootstrap-report.md",
        ".state/bootstrap-rerun-report.md",
        ".state/sqlite-bootstrap.pending.md",
        ".state/sqlite-bootstrap.report.md",
        ".state/workspace-validation.md",
    ];

    let paths: Vec<String> = manifest_content
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|l| {
            if l.contains('\t') {
                l.split('\t').next().unwrap_or("").trim().to_string()
            } else {
                l.to_string()
            }
        })
        .filter(|p| !p.is_empty())
        .filter(|p| !runtime_state.contains(&p.as_str()))
        .filter(|p| {
            let full = target.join(p.replace('/', std::path::MAIN_SEPARATOR_STR));
            full.exists()
        })
        .collect();

    if paths.is_empty() {
        return Ok(String::new());
    }

    // Check for pre-existing staged files
    let pre_staged = std::process::Command::new("git")
        .args(["diff", "--cached", "--name-only"])
        .current_dir(target)
        .output()?;
    let pre_staged_str = String::from_utf8_lossy(&pre_staged.stdout);
    let foreign: Vec<&str> = pre_staged_str
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty() && !paths.contains(&l.to_string()))
        .collect();

    if !foreign.is_empty() {
        bail!(
            "Git index contains staged files outside the bootstrap manifest:\n  {}\nCommit or unstage before bootstrap commit.",
            foreign.join("\n  ")
        );
    }

    // Stage and commit
    for p in &paths {
        let _ = std::process::Command::new("git")
            .args(["add", "--", p])
            .current_dir(target)
            .status();
    }

    let status_check = std::process::Command::new("git")
        .args(["diff", "--cached", "--name-only"])
        .current_dir(target)
        .output()?;
    if status_check.stdout.is_empty() {
        return Ok(String::new());
    }

    std::process::Command::new("git")
        .args(["commit", "-m", message])
        .current_dir(target)
        .status()?;

    let hash = util::command_output("git", &["-C", &target.to_string_lossy(), "rev-parse", "--short", "HEAD"])?;
    Ok(hash)
}

fn install_pre_commit_hook(target: &Path) -> Result<()> {
    let hooks_dir = target.join(".git").join("hooks");
    fs::create_dir_all(&hooks_dir)?;
    let hook_path = hooks_dir.join("pre-commit");
    let hook_content = "#!/bin/sh\nset -eu\nREPO_ROOT=$(git rev-parse --show-toplevel)\nBASE_DIR=\"$REPO_ROOT/.agents/bin/prd-to-product-agents\"\nCLI=\"\"\ncase \"$(uname -s)\" in\n  Darwin) CLI=\"$BASE_DIR/prdtp-agents-functions-cli-darwin-arm64\" ;;\n  Linux) CLI=\"$BASE_DIR/prdtp-agents-functions-cli-linux-x64\" ;;\n  MINGW*|MSYS*|CYGWIN*|Windows_NT) CLI=\"$BASE_DIR/prdtp-agents-functions-cli-windows-x64.exe\" ;;\n  *) : ;;\nesac\nif [ -z \"$CLI\" ] || [ ! -f \"$CLI\" ]; then\n  if [ -f \"$BASE_DIR/prdtp-agents-functions-cli-windows-x64.exe\" ]; then\n    CLI=\"$BASE_DIR/prdtp-agents-functions-cli-windows-x64.exe\"\n  elif [ -f \"$BASE_DIR/prdtp-agents-functions-cli-darwin-arm64\" ]; then\n    CLI=\"$BASE_DIR/prdtp-agents-functions-cli-darwin-arm64\"\n  elif [ -f \"$BASE_DIR/prdtp-agents-functions-cli-linux-x64\" ]; then\n    CLI=\"$BASE_DIR/prdtp-agents-functions-cli-linux-x64\"\n  fi\nfi\nif [ -z \"$CLI\" ] || [ ! -f \"$CLI\" ]; then\n  echo \"[CRITICAL] Pre-commit hook failed: Target CLI binary not found in $BASE_DIR!\" >&2\n  exit 1\nfi\nexec \"$CLI\" --workspace \"$REPO_ROOT\" git pre-commit-validate \"$@\"\n";
    util::write_utf8(hook_path.as_path(), hook_content)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&hook_path, perms)?;
    }

    Ok(())
}

fn mark_workspace_bootstrapped(target: &Path) -> Result<()> {
    let governance_path = target.join(".github").join("github-governance.yaml");
    if !governance_path.exists() {
        return Ok(());
    }

    let content = fs::read_to_string(&governance_path)?;
    let updated = content.replace("status: template", "status: bootstrapped");
    if updated != content {
        util::write_utf8_lf(&governance_path, &updated)?;
    }
    Ok(())
}

fn file_has_placeholders(path: &Path) -> bool {
    fs::read_to_string(path)
        .map(|content| {
            content.contains("REPLACE_ME")
                || content.contains("@team-")
                || content.contains("TODO")
                || content.contains("PLACEHOLDER")
                || content.contains("your-org")
                || content.contains("your-repo")
        })
        .unwrap_or(false)
}

fn detect_governance_status(target: &Path) -> &'static str {
    let governance_path = target.join(".github").join("github-governance.yaml");
    let codeowners_path = target.join(".github").join("CODEOWNERS");
    if !governance_path.exists() || !codeowners_path.exists() {
        return "pending_configuration";
    }
    if file_has_placeholders(&governance_path) || file_has_placeholders(&codeowners_path) {
        return "pending_configuration";
    }
    "configured"
}

fn detect_readiness_status(target: &Path, governance_status: &str) -> &'static str {
    if governance_status != "configured" {
        return "not_ready";
    }
    let governance_path = target.join(".github").join("github-governance.yaml");
    if let Ok(content) = fs::read_to_string(governance_path) {
        if content.contains("status: configured") || content.contains("status: production-ready") {
            return "ready";
        }
    }
    "not_ready"
}

fn collect_manual_next_steps(
    target: &Path,
    governance_status: &str,
    github_owner: &str,
    github_repo: &str,
) -> Vec<String> {
    let mut steps = Vec::new();
    if governance_status == "pending_configuration" {
        let owner = if github_owner.is_empty() {
            "<owner>"
        } else {
            github_owner
        };
        let repo = if github_repo.is_empty() {
            "<repo>"
        } else {
            github_repo
        };
        steps.push(format!(
            "run `prdtp-agents-functions-cli --workspace . governance configure --owner {owner} --repo {repo} --release-gate-login <release-gate-login> --reviewer-product <@product-owner> --reviewer-architecture <@architecture-reviewer> --reviewer-tech-lead <@tech-lead-reviewer> --reviewer-qa <@qa-reviewer> --reviewer-devops <@devops-reviewer> --reviewer-infra <@infra-reviewer>`"
        ));
        steps.push("rerun `prdtp-agents-functions-cli --workspace . validate governance` after governance configure".to_string());
        steps.push("rerun `prdtp-agents-functions-cli --workspace . validate readiness` once governance and capabilities are intentional".to_string());
    }
    if !target.join(".state").join("project_memory.db").exists() {
        steps.push("install sqlite3 and run prdtp-agents-functions-cli --workspace . database init if you want the SQLite mirror".to_string());
    }
    steps
}

fn run_workspace_validation(target: &Path) -> bool {
    use prdtp_agents_shared::workspace_paths;

    let mut pass = true;

    // Check required directories
    let required_dirs = [".github", "docs/project", ".github/agents", ".github/prompts"];
    for dir in &required_dirs {
        if !target.join(dir).is_dir() {
            eprintln!("  {} missing directory: {dir}", "FAIL:".red());
            pass = false;
        }
    }

    // Check shared required files list
    for file in workspace_paths::REQUIRED_FILES {
        if !target.join(file).exists() {
            eprintln!("  {} missing required file: {file}", "FAIL:".red());
            pass = false;
        }
    }

    // Check agent files
    let agents_dir = target.join(".github/agents");
    for agent in workspace_paths::AGENT_NAMES {
        if !agents_dir.join(format!("{agent}.agent.md")).exists() {
            eprintln!("  {} missing agent: {agent}.agent.md", "FAIL:".red());
            pass = false;
        }
    }

    pass
}
